### ISSUE TITLE
Upgrading to latest clang

### ISSUE THREAD

**Issue by tpudlik** [bazelembedded/rules_cc_toolchain#44]
The clang version currently used in rules_cc_toolchain is pretty old (12.0.0, from April 2021) and that bugs in the C++20 implementation (it doesn't know about the iterator constructor for std::span). I'd like to take a stab at upgrading to the latest clang (15.0.7).

@silvergasp I wanted to reach out before working on a PR in case you had words of warning or objections.

**Comment by silvergasp** [comment]
No objections from me. I'd be happy to accept a PR.

**Comment by tpudlik** [comment]
I have a draft PR upgrading to 15.0.6 (https://github.com/bazelembedded/rules_cc_toolchain/pull/45), but it doesn't quite work yet. I run into trouble finding `__config_site`:

```
ERROR: /usr/local/google/home/tpudlik/bazelembedded/rules_cc_toolchain/tests/BUILD.bazel:9:8: Compiling tests/dummy_test1.cc failed: (Exit 1): gcc failed: error executing command (from target //tests:dummy_test1
) cc_toolchain/wrappers/posix/gcc -MD -MF bazel-out/k8-fastbuild/bin/tests/_objs/dummy_test1/dummy_test1.pic.d '-frandom-seed=bazel-out/k8-fastbuild/bin/tests/_objs/dummy_test1/dummy_test1.pic.o' -fPIC ... (rema
ining 31 arguments skipped)                                                                                                                                                                                        
                                                                                                                                                                                                                   
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging                                                                                                       
In file included from tests/dummy_test1.cc:1:                                                                                                                                                                      
In file included from external/clang_llvm_x86_64_linux_gnu_ubuntu/include/c++/v1/iostream:36:                                                                                                                      
In file included from external/clang_llvm_x86_64_linux_gnu_ubuntu/include/c++/v1/__assert:13:                                                                                                                      
external/clang_llvm_x86_64_linux_gnu_ubuntu/include/c++/v1/__config:13:10: fatal error: '__config_site' file not found                                                                                             
#include <__config_site>    
```

That file is not in `include/c++/v1`, but in `include/x86_64-unknown-linux-gnu/c++/v1/`.  But if I add the latter path to the `includes` for the `llvm_libcxx` target, I get problems with `include_next`:

```
In file included from external/clang_llvm_x86_64_linux_gnu_ubuntu/include/c++/v1/wchar.h:109:                                                                                                                      
external/clang_llvm_x86_64_linux_gnu_ubuntu/include/c++/v1/stddef.h:45:15: fatal error: 'stddef.h' file not found                                                                                                  
#include_next <stddef.h>                                                                                                                                                                                           
              ^~~~~~~~~~                                                                                                                                                                                           
1 error generated.   
```

I saw some possibly relevant issues that suggest this clang release may not have been built with the correct flags (https://github.com/llvm/llvm-project/issues/57104). Interestingly, there's no "vanilla" x86 Linux release for 15.0.7, the latest version; 15.0.6 was the last one.

**Comment by silvergasp** [comment]
Yeah getting the include ordering for system libs and `include_next` is rather finicky. As soon as you deviate slightly from the norm you have to deal with all of these shenanigans. Essentially the `deps` attribute of cc_toolchain_import manages the ordering of includes, e.g. if you have;
```python
cc_toolchain_import(
   name = "foo",
  #...
  deps = [":bar"],
)
cc_toolchain_import(
   name = "bar",
   #...
)
```
The include search paths will be added to the command line from `foo` first and `bar` second, this is the mechanism that is required to get `include_next` working correctly.

The reason I went with this approach was that if you use buildifier for formatting, it'll alphabetically order all your lists. But when include ordering is actually important (i.e. with include_next), this just causes a bunch of headaches. So the workaround was just to control include ordering using the nested dependency tree and the deps attribute :) This ends up working out nicely as well because typically if you are using `include_next` you are saying hey include this from one of my dependencies.

Some handy tips for debugging these errors are;
```
# Follow bazel's endless symlinks from your workspace
find -L . -name stddef.h
# Find out what clangs default include paths are
bazel run @clang_llvm_x86_64_linux_gnu_ubuntu//:bin/clang++ -- -E -Wp,-v -xc++ /dev/null
```

**Comment by tpudlik** [comment]
I am a compiler newbie, so I'm just bumbling about. Not clear if things are getting better rather than worse!

So, I understand that when I get the error,

```
external/clang_llvm_x86_64_linux_gnu_ubuntu/include/c++/v1/stddef.h:45:15: fatal error: 'stddef.h' file not found                                                                                                  
#include_next <stddef.h>  
```

this indicates there should be an include search path in the compile command, occurring after `clang_llvm_x86_64_linux_gnu_ubuntu/include/c++/v1`, that provides `stddef.h`. And your helpful command, `find -L . -name stddef.h`, lists three such possible paths:

```
$ find -L . -name stddef.h
./bazel-rules_cc_toolchain/external/clang_llvm_x86_64_linux_gnu_ubuntu/lib/clang/15.0.6/include/stddef.h
./bazel-rules_cc_toolchain/external/clang_llvm_x86_64_linux_gnu_ubuntu/include/c++/v1/stddef.h
./bazel-rules_cc_toolchain/external/debian_stretch_amd64_sysroot/usr/lib/gcc/x86_64-linux-gnu/6/include/stddef.h
./bazel-rules_cc_toolchain/external/debian_stretch_amd64_sysroot/usr/include/linux/stddef.h
```

(I say three, because the second of those four paths is the header containing the problematic `#include_next <stddef.h> `.) But now, how do I know which of these paths is the one that `#include_next` is hoping to find? Is it the one that appears in the output of `bazel run @clang_llvm_x86_64_linux_gnu_ubuntu//:bin/clang++ -- -E -Wp,-v -xc++ /dev/null`? On my machine that lists a bunch of local system paths and `external/clang_llvm_x86_64_linux_gnu_ubuntu/lib/clang/15.0.6/include`. So, perhaps that is what we want?

I went ahead and  created a special `cc_toolchain_import` target for this header, and made it a dep of `llvm_libcxx`. (See next commit in PR.) That fixes the `include_next` problem, but produces another:

```
external/clang_llvm_x86_64_linux_gnu_ubuntu/include/c++/v1/cstddef:50:9: error: no member named 'nullptr_t' in the global namespace                                                                                
using ::nullptr_t;
```

I think `nullptr_t` is ordinarily provided by `#include <cstddef>`, so this seems to suggest that I (1) successfully added another location containing `stddef.h` to the include search path, thus silencing the `#include_next` error, but (2) that location doesn't actually contain the right header, since I'm now missing the actual contents of `cstddef`.

**Comment by tpudlik** [comment]
Actually, I see the error of my ways: I tried to put globs in `includes` to remove version numbers. But that doesn't work, of course! Now that I removed these, I can get the in-repo tests to compile, at least. Will upload new commits to the PR soon.

**Comment by silvergasp** [comment]
> (I say three, because the second of those four paths is the header containing the problematic #include_next <stddef.h> .) But now, how do I know which of these paths is the one that #include_next is hoping to find?

So typically if you have a libc header under a c++ directory it'll just be a kind of internal redirect, which is why you see the "#include_next" under `./bazel-rules_cc_toolchain/external/clang_llvm_x86_64_linux_gnu_ubuntu/include/c++/v1/stddef.h`. As far as I understand this allows libcxx to create a kind of shim layer to account for some of the quirks between different versions of libc e.g. musl, gnu, newlib etc. So an include next from a libc++ should usually point to libc.

> Is it the one that appears in the output of bazel run @clang_llvm_x86_64_linux_gnu_ubuntu//:bin/clang++ -- -E -Wp,-v -xc++ /dev/null? On my machine that lists a bunch of local system paths and external/clang_llvm_x86_64_linux_gnu_ubuntu/lib/clang/15.0.6/include. So, perhaps that is what we want?

If your machine is based on debian, this will likely work as expected as we are using a Debian sysroot for this build. This `--sysroot` flag will override absolute includes relative to the sysroot path. So it's still a useful output. If you want to be more precise you could modify that command to be something like;

`bazel run @clang_llvm_x86_64_linux_gnu_ubuntu//:bin/clang++ -- -E -Wp,-v -xc++ --sysroot=./bazel-rules_cc_toolchain/external/debian_stretch_amd64_sysroot /dev/null`

> Actually, I see the error of my ways: I tried to put globs in includes to remove version numbers. But that doesn't work, of course! Now that I removed these, I can get the in-repo tests to compile, at least. Will upload new commits to the PR soon.

Oh yeah that would do it :)
